- hosts: all
  tasks:
  - name: Install aptitude using apt
    apt: 
     name: aptitude
     state: latest
     update_cache: yes
     force_apt_get: yes
 
  - name: Install docker dependencies
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      state: present

  - name: CURL Docker repository
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt-get repo and cache
    apt:
      update_cache=yes
  - name: Upgrade all apt packages
    apt:
      upgrade=dist

  - name: Install docker engine
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Enable service docker, and enable persistently
    service: 
      name: docker 
      enabled: yes
  
  - name: Add Google official GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  
  - name: Add Kubernetes Repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
      state: present
      filename: kubernetes
      mode: 0600
  
  - name: Installing Kubernetes Cluster Packages.
    apt: 
      name:
        - kubeadm
        - kubectl
        - kubelet
      state: present
  
  - name: Enable service kubelet, and enable persistently
    service: 
      name: kubelet
      enabled: yes
  
  - name: Reboot all the kubernetes nodes.
    reboot:
      post_reboot_delay: 10
      reboot_timeout: 60
      connect_timeout: 60
      test_command: uptime
  
  - pause: seconds=20
